export const DELETE_RECORD = "DELETE_RECORD";
export const ADD_RECORD = "ADD_RECORD";
export const CHANGE_RECORD = "CHANGE_RECORD";

export const DELETE_SELECTED = "DELETE_SELECTED";
export const CHANGE_SELECTED = "CHANGE_SELECTED";

export const FETCH_RECORDS = "FETCH_RECORDS";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";

export const SET_FILTER = "SET_FILTER";